version: "3.1"

volumes:
  strapi:
    driver: local

services:
  strapi-mysql:
    image: mysql:8.0
    # NOTE: use of "mysql_native_password" is not recommended this is just an example for local config, not intended to be a production configuration
    # https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: strapidb
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - strapi:/var/lib/mysql
    #   - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    restart: always
    ports:
      - "7000:8080"
