version: "3.1"

volumes:
  strapi:
    driver: local

networks:
  strapi:
    name: strapi
    driver: bridge

services:
  strapi:
    platform: linux/amd64 #for platform error on Apple M1 chips
    container_name: strapi
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT:-mysql2}
      DATABASE_HOST: strapi-mysql
      DATABASE_PORT: ${DATABASE_PORT:-3306}
      DATABASE_NAME: ${DATABASE_NAME:-strapidb}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-admin}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-secret}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV:-production}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapi-mysql
      - adminer

  strapi-mysql:
    image: mysql:8.0
    # NOTE: use of "mysql_native_password" is not recommended this is just an example for local config, not intended to be a production configuration
    # https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME:-strapidb}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-secret}
      MYSQL_USER: ${DATABASE_USERNAME:-admin}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-secret}
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - strapi:/var/lib/mysql
    #   - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - strapi

  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      - ADMINER_DEFAULT_SERVER=strapi-mysql
    ports:
      - "7000:8080"
    networks:
      - strapi
    depends_on:
      - strapi-mysql
